name: ble_ota_app
description: Upload firmware over bluetooth.
publish_to: 'none'
version: 2.0.0+13

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ble_backend: ^1.4.0
  ble_backend_factory: ^1.4.2
  ble_ota: ^2.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.3
  http: ^1.5.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.1.0
  wakelock_plus: ^1.4.0
  expandable: ^5.0.1
  meta: ^1.16.0
  jumping_dot: ^0.0.7
  easy_localization: ^3.0.8
  flutter_markdown: ^0.7.7
  flutter_pin_code_fields: ^2.2.0
  flutter_settings_screens: ^0.3.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

icons_launcher:
  image_path: "assets/images/icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/icon.png"
      adaptive_background_color: '#ffffff'
      adaptive_foreground_image: "assets/images/icon_color_foreground.png"
      adaptive_monochrome_image: "assets/images/icon_mono_foreground.png"
    ios:
      enable: true
      image_path: "assets/images/icon.png"
    web:
      enable: true
      image_path: "assets/images/icon.png"
      favicon_path: "assets/images/icon.png"
    macos:
      enable: true
      image_path: "assets/images/icon.png"
    windows:
      enable: true
      image_path: "assets/images/icon.png"
    linux:
      enable: false
      image_path: "assets/images/icon.png"