name: ble_ota_app
description: Upload firmware over bluetooth.
publish_to: 'none'
version: 1.1.0+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ble_backend: ^1.2.2
  ble_backend_factory: ^1.1.2
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  archive: ^3.6.1
  permission_handler: ^11.3.1
  http: ^1.2.2
  wakelock_plus: ^1.2.8
  expandable: ^5.0.1
  meta: ^1.15.0
  flutter_settings_screens: ^0.3.4
  jumping_dot: ^0.0.7
  easy_localization: ^3.0.7
  flutter_markdown: ^0.7.3
  flutter_pin_code_fields: ^2.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

icons_launcher:
  image_path: "assets/images/icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/icon.png"
      adaptive_background_color: '#ffffff'
      adaptive_foreground_image: "assets/images/icon_color_foreground.png"
      adaptive_monochrome_image: "assets/images/icon_mono_foreground.png"
    ios:
      enable: true
      image_path: "assets/images/icon.png"
    web:
      enable: true
      image_path: "assets/images/icon.png"
      favicon_path: "assets/images/icon.png"
    macos:
      enable: true
      image_path: "assets/images/icon.png"
    windows:
      enable: true
      image_path: "assets/images/icon.png"
    linux:
      enable: false
      image_path: "assets/images/icon.png"