name: ble_ota_app
description: Upload firmware over bluetooth.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_reactive_ble: ^5.3.1
  file_picker: ^8.0.3
  archive: ^3.6.0
  permission_handler: ^11.3.1
  http: ^1.2.1
  wakelock_plus: ^1.2.5
  expandable: ^5.0.1
  meta: ^1.12.0
  flutter_settings_screens: ^0.3.4
  jumping_dot: ^0.0.6
  easy_localization: ^3.0.7
  flutter_markdown: ^0.7.1
  flutter_pin_code_fields: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

icons_launcher:
  image_path: "assets/images/icon_border.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/icon_border.png"
      adaptive_background_color: '#2f4250'
      adaptive_foreground_image: "assets/images/icon_round.png"
      adaptive_round_image: "assets/images/icon_round.png"
      adaptive_monochrome_image: "assets/images/icon_round_mono.png"
    ios:
      enable: true
      image_path: "assets/images/icon_border.png"
    web:
      enable: true
      image_path: "assets/images/icon_border.png"
      favicon_path: "assets/images/icon_round.png"
    macos:
      enable: true
      image_path: "assets/images/icon_border.png"
    windows:
      enable: true
      image_path: "assets/images/icon_border.png"
    linux:
      enable: false
      image_path: "assets/images/icon_border.png"